<?php

return [

    // Master switches (see docs/notices-plan.md rollout order).
    'fetch_enabled' => env('NOTICES_FETCH_ENABLED', false),
    'autopublish_enabled' => env('NOTICES_AUTOPUBLISH_ENABLED', false),
    'notifications_enabled' => env('NOTICES_NOTIFICATIONS_ENABLED', false),
    'social_enabled' => env('NOTICES_SOCIAL_ENABLED', false),

    'alert_email' => env('NOTICES_ALERT_EMAIL'),
    // Notice jobs always go to their own queue on the database connection, so
    // the cron-driven worker (routes/console.php) only ever runs these jobs,
    // whatever QUEUE_CONNECTION the rest of the app uses.
    'queue' => env('NOTICES_QUEUE', 'notices'),
    'queue_connection' => env('NOTICES_QUEUE_CONNECTION', 'database'),

    // Public site - used for links in emails/RSS generated by the backend.
    'site_url' => rtrim(env('NOTICES_SITE_URL', 'https://www.examsnepal.com'), '/'),

    'http' => [
        'user_agent' => 'ExamsNepalBot/1.0 (+https://www.examsnepal.com/bot)',
        'timeout' => 25,
        'retries' => 3,
        // Minimum gap between two requests to the same host.
        'per_host_delay_ms' => 2000,
        'max_download_bytes' => 15 * 1024 * 1024,
        'robots_cache_minutes' => 24 * 60,
    ],

    'health' => [
        'max_consecutive_failures' => 5,
        'max_consecutive_empty_runs' => 3,
    ],

    'dedup' => [
        // Same organization + similar title within this window = duplicate.
        'fuzzy_window_days' => 7,
        'fuzzy_similarity' => 90, // percent, code-point Levenshtein on normalized titles
    ],

    'archive_after_deadline_days' => 30,

    // Titles matching this are stored as `rejected` straight away (kept for
    // audit) without spending an API call - tenders, bids, auctions.
    'irrelevant_title_regex' => '(बोलपत्र|दरभाउपत्र|सिलबन्दी|लिलाम|टेण्डर|टेन्डर|खरिद सम्बन्धी|ई-बिडिङ|\\btender\\b|\\bbid(s|ders?|ding)?\\b|\\bauction\\b|\\bprocurement\\b|expression of interest|\\beoi\\b|quotation)',

    // Items published longer ago than this are ignored at ingestion, so a
    // new source doesn't backfill years of old notices.
    'max_item_age_days' => 45,

    'ai' => [
        // none (publish title + date + official link only, no AI calls),
        // openrouter (one key for Gemini, Claude, ...) or anthropic.
        'provider' => env('NOTICES_AI_PROVIDER', 'none'),
        'openrouter' => [
            'api_key' => env('OPENROUTER_API_KEY'),
            'base_url' => env('OPENROUTER_BASE_URL', 'https://openrouter.ai/api/v1'),
            // "schema" = strict JSON-schema output (paid Gemini/Claude models);
            // "json_object" = plain JSON mode for models without it (the free
            // Gemma models) - the schema is then given in the prompt instead.
            'json_mode' => env('NOTICES_AI_JSON_MODE', 'schema'),
            // How OpenRouter reads PDFs the backend could not extract text from:
            // native (model reads the PDF; paid Gemini/Claude), cloudflare-ai
            // (free markdown conversion, for models without file input) or
            // mistral-ocr (paid OCR, best for scanned notices).
            'pdf_engine' => env('NOTICES_AI_PDF_ENGINE', 'native'),
        ],
        // Max AI requests per day (0 = no limit). OpenRouter free models allow
        // 50/day (1000/day once $10 of credit has ever been bought); when the
        // cap is reached, enrichment waits until the next day.
        'daily_request_limit' => (int) env('NOTICES_AI_DAILY_LIMIT', 0),
        'anthropic' => [
            'api_key' => env('ANTHROPIC_API_KEY'),
        ],
        // First pass for normal notices; the fallback handles low-confidence
        // results, long documents and scanned PDFs/images. Model ids are in
        // the provider's format (OpenRouter: "vendor/model").
        'model' => env('NOTICES_AI_MODEL', env('NOTICES_AI_PROVIDER', 'openrouter') === 'anthropic' ? 'claude-haiku-4-5' : 'google/gemini-2.5-flash'),
        'fallback_model' => env('NOTICES_AI_FALLBACK_MODEL', env('NOTICES_AI_PROVIDER', 'openrouter') === 'anthropic' ? 'claude-sonnet-5' : 'google/gemini-3.8-flash'),
        'max_tokens' => 4096,
        // Below this the fallback model gets a second pass.
        'fallback_below_confidence' => 0.6,
        'autopublish_min_confidence' => 0.8,
        // Characters of extracted text sent to the model.
        'max_text_chars' => 24000,
        // PDFs larger than this are not sent as document blocks.
        'max_pdf_bytes' => 10 * 1024 * 1024,
    ],

    // Tags the model may assign, in addition to the slugs of every published
    // exam guide (those are added at runtime by NoticeTagVocabulary). Each
    // maps to the /find-mcq category that holds its mock tests.
    'fixed_exam_tags' => [
        'kharidar' => 'administration-loksewa-all-levels-exams',
        'nayab-subba' => 'administration-loksewa-all-levels-exams',
        'section-officer' => 'administration-loksewa-all-levels-exams',
        'computer-operator' => 'administration-loksewa-all-levels-exams',
        'health-assistant' => 'medical-nmcle-loksewa-mdms-exams',
        'medical-officer' => 'medical-nmcle-loksewa-mdms-exams',
        'staff-nurse' => 'nursing-pcl-bns-bsc-nursing-mn-entrance-loksewa-license-exams',
        'engineer-loksewa' => 'civil-engineering-license-loksewa-exams',
        'sub-engineer' => 'civil-engineering-license-loksewa-exams',
        'agriculture-loksewa' => 'agriculture-all-level-exams',
        'banking' => 'administration-loksewa-all-levels-exams',
        'nepal-police' => 'administration-loksewa-all-levels-exams',
        'nepal-army' => 'administration-loksewa-all-levels-exams',
        'apf' => 'administration-loksewa-all-levels-exams',
        'teacher-tsc' => 'administration-loksewa-all-levels-exams',
        'mbbs-cee' => 'mbbs-entrance-exams',
        'bsc-nursing-cee' => 'nursing-pcl-bns-bsc-nursing-mn-entrance-loksewa-license-exams',
        'md-ms-entrance' => 'medical-nmcle-loksewa-mdms-exams',
        'mds-entrance' => 'dental-nmcle-loksewa-mds-exams',
        'ioe-be-entrance' => 'be-entrance-exams',
        'ioe-msc-entrance' => 'be-entrance-exams',
        'csit-entrance' => null,
        'cmat' => null,
        'ctevt-entrance' => null,
        'nmc-license' => 'medical-nmcle-loksewa-mdms-exams',
        'nmc-dental-license' => 'dental-nmcle-loksewa-mds-exams',
        'nnc-license' => 'nursing-pcl-bns-bsc-nursing-mn-entrance-loksewa-license-exams',
        'npc-license' => 'pharmacology-license-loksewa-exams',
        'nhpc-license' => 'radiography-diploma-bsc-msc-loksewa-exams',
        'nec-license' => 'engineering-license-nec-loksewa-me-exams',
        'bar-license' => null,
        'ca-exam' => null,
        'tsc-license' => 'administration-loksewa-all-levels-exams',
        'veterinary-license' => 'agriculture-all-level-exams',
        'ayurveda-license' => null,
    ],

    'sub_categories' => [
        'loksewa' => ['federal_psc', 'provincial_psc', 'tsc', 'security_forces', 'corporation', 'bank', 'local_level', 'other'],
        'entrance' => ['medical_entrance', 'pg_entrance', 'engineering_entrance', 'science_entrance', 'management_entrance', 'university_entrance', 'ctevt_entrance', 'other'],
        'license' => ['medical_license', 'dental_license', 'nursing_license', 'pharmacy_license', 'health_professional_license', 'engineering_license', 'law_license', 'ca_license', 'veterinary_license', 'ayurveda_license', 'teaching_license', 'other'],
    ],

    'provinces' => ['koshi', 'madhesh', 'bagmati', 'gandaki', 'lumbini', 'karnali', 'sudurpashchim'],
];
